// =============================================================================
// ChildProfileService — the species text, in a child's register (SAM-11)
// =============================================================================
//
// The app already ships offline species descriptions in eleven languages
// (`SpeciesDescriptionService`). They are accurate, they are translated, and
// they are written for adults: "Vorkommen in offenen Landschaften mit
// eingestreuten Gehölzen" is a true sentence that an eight-year-old will not
// read twice. `SAM-11` asks for a **rewrite, not a translation**.
//
// ### Why this is a separate file rather than another bundle locale
//
// Because it is a different *kind* of text and has a different lifecycle. The
// adult descriptions are generated by `tools/build_species_bundle.py` from the
// taxonomy; these are written by a person, one species at a time, and there
// will never be as many of them. Merging the two would mean a regeneration of
// the bundle could silently overwrite editorial work.
//
// ### Only two languages, on purpose
//
// `SET-10`'s recommendation, and it is the honest one: German first, English
// second, every other locale keeping the adult description until someone funds
// the rewrite. A machine translation of a *deliberately chosen register* is
// worse than the adult text it replaced — it reads as neither one thing nor
// the other, and the whole value of `SAM-11` is the register.
//
// So a missing profile is the ordinary case, not an error, and the caller
// falls back rather than showing a gap.
// =============================================================================

import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show AssetBundle, rootBundle;
import 'package:meta/meta.dart';

/// One species, written for a child (`SAM-11`).
@immutable
class ChildProfile {
  const ChildProfile({required this.text, this.call});

  /// Two or three sentences: what it looks like, and one thing worth knowing.
  final String text;

  /// How to recognise the voice (`SAM-12`).
  ///
  /// Null where no honest mnemonic exists. Inventing one would teach a child
  /// something false about a bird, which is worse than saying nothing — so
  /// this is deliberately not filled in for every species.
  final String? call;

  bool get hasCall => call != null && call!.trim().isNotEmpty;
}

/// Loads the hand-written child-register profiles.
class ChildProfileService {
  ChildProfileService({AssetBundle? bundle}) : _bundle = bundle;

  /// Injectable so a test does not need the real asset.
  final AssetBundle? _bundle;

  /// Its own directory, and not `assets/species_data/`: that one holds the
  /// *generated* bundle and is gitignored wholesale, so an authored file put
  /// there would never be committed and a cleanup would delete it. Separate
  /// directories for generated and written content, which is the same
  /// distinction the class comment makes.
  static const String assetPath = 'assets/species_profiles/child_profiles.json';

  /// The locales a rewrite exists for (`SET-10`).
  static const List<String> availableLocales = ['de', 'en'];

  Map<String, Map<String, ChildProfile>>? _profiles;

  Future<void> _load() async {
    if (_profiles != null) return;

    try {
      final raw = await (_bundle ?? rootBundle).loadString(assetPath);
      final decoded = jsonDecode(raw) as Map<String, dynamic>;

      _profiles = {
        for (final entry in decoded.entries)
          // The file carries its own editorial note under `_readme`, so the
          // rules live beside the data rather than only in this comment.
          if (!entry.key.startsWith('_') && entry.value is Map)
            entry.key: {
              for (final byLocale
                  in (entry.value as Map<String, dynamic>).entries)
                if (byLocale.value is Map)
                  byLocale.key: ChildProfile(
                    text:
                        (byLocale.value as Map<String, dynamic>)['text']
                            as String? ??
                        '',
                    call:
                        (byLocale.value as Map<String, dynamic>)['call']
                            as String?,
                  ),
            },
      };
    } catch (error, stack) {
      debugPrint(
        '[ChildProfileService] could not load $assetPath: '
        '$error\n$stack',
      );
      // An empty map rather than a rethrow: every species falls back to the
      // adult description, which is exactly what happens for the hundred
      // species that have no rewrite yet.
      _profiles = {};
    }
  }

  /// The child-register profile for [scientificName] in [locale], or null.
  ///
  /// Null is ordinary. The caller shows the bundled adult description
  /// instead — never a gap, and never a half-translated sentence.
  Future<ChildProfile?> profileFor(String scientificName, String locale) async {
    await _load();

    final byLocale = _profiles![scientificName];
    if (byLocale == null) return null;

    // `de_DE`, `de-AT` and `de` all want the German text; anything else that
    // has no rewrite falls through to null rather than to English, because a
    // Czech child reading an English paragraph is worse served than one
    // reading the Czech adult description.
    final language = locale.split(RegExp('[-_]')).first.toLowerCase();
    return byLocale[language];
  }

  /// How many species have been rewritten. For diagnostics and the tests.
  @visibleForTesting
  Future<int> get profileCount async {
    await _load();
    return _profiles!.length;
  }
}
